### ISSUE TITLE
[Counter AutoPluginReloader] 镜像服切换工作目录时该插件会自动卸载与主服务器同样的插件，并在镜像服目录切换回主服务器不重新加载

### ISSUE THREAD

**Issue by tangsu99** [EMUnion/MirrorServerReforged#2]
在完全配置好之后，执行!!msr start，主服务器MCDR插件会被卸载，(大概)插件加载目录变更出现问题， 主服内执行!!MCDR plg list 指令显示只加载到部分插件（!!msr 指令无效），并且直接在控制台输入指令服务端会无法正常接收到指令，重启服务端会恢复
感觉问题描述不是很清楚qwq
MCDR版本：`2.3.2`
插件版本：`1.0.3`
python版本：`3.8.6`
系统：`Windows11 21H2 22000.593`
config内command：`python -m mcdreforged`
主服务器 MCDR config内start_command：run.bat （`java -jar -Xms128M -Xmx8G -server -Dlog4j2.formatMsgNoLookups=true fabric-server-launch.jar nogui`）
Mirror MCDR config内start_command：`java -Xms1G -Xmx4G -jar fabric-server-launch.jar nogui`

**Comment by GamerNoTitle** [comment]
好的 我先下载下来看下log先

**Comment by GamerNoTitle** [comment]
你这个情况是间歇性的还是一直存在 我目前没存在你这个问题
你试试开启主服务器，然后开启镜像服，接着直接关掉镜像服，最后关掉主服务器，把logs文件夹里面的`MCDR.log`文件传给我

**Comment by tangsu99** [comment]
> 你这个情况是间歇性的还是一直存在 我目前没存在你这个问题 你试试开启主服务器，然后开启镜像服，接着直接关掉镜像服，最后关掉主服务器，把logs文件夹里面的`MCDR.log`文件传给我

每次都会出现这种情况（总感觉是win11的锅）
```
[MCDR] [2022-04-17 17:35:29] [MainThread/INFO]: MCDReforged正于Python 3.8.6环境中运行
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 auto_plugin_reloader@1.0.1 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 bilibiliinfo@1.0.0 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 biliwiki@1.0.0 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 daycount_nbt@2.0.2 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 join_motd@1.2.0 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 kick_time_plugin@1.0.0 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.4.1 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 mc_uuid@1.0.0 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 mirror_server_reforged@1.0.3 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 playerlist_getter@1.0.0 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.3.3 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 插件 simple_here@1.0.0 已加载
[MCDR] [2022-04-17 17:35:29] [TaskExecutor/INFO]: 共加载: §712§r 个插件; 已加载插件数: §714§r
[MCDR] [2022-04-17 17:35:29] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -Xms128M -Xmx2048M -jar fabric-server-launch.jar nogui"
[MCDR] [2022-04-17 17:35:29] [MainThread/INFO]: 服务端正在以 PID 20868 运行中
[MCDR] [2022-04-17 17:35:30] [CheckUpdate/INFO]: MCDR 已为最新版
[MCDR] [2022-04-17 17:35:52] [TaskExecutor/INFO]: rcon 已连接
[MCDR] [2022-04-17 17:36:03] [TaskExecutor/INFO]: §b[MirrorServerReforged] §6镜像服未运行！
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 刷新所有变更的插件中
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 auto_plugin_reloader@1.0.1 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 bilibiliinfo@1.0.0 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 biliwiki@1.0.0 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 daycount_nbt@2.0.2 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 join_motd@1.2.0 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 kick_time_plugin@1.0.0 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 mc_uuid@1.0.0 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.4.1 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 mirror_server_reforged@1.0.3 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 playerlist_getter@1.0.0 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.3.3 已卸载
[MCDR] [2022-04-17 17:36:10] [TaskExecutor/INFO]: 插件 simple_here@1.0.0 已卸载
[MCDR] [2022-04-17 17:38:56] [TaskExecutor/INFO]: rcon 已断开连接
[MCDR] [2022-04-17 17:38:58] [MainThread/INFO]: 等待服务端进程停止
[MCDR] [2022-04-17 17:38:58] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [2022-04-17 17:38:58] [MainThread/INFO]: 服务端已关闭
[MCDR] [2022-04-17 17:38:58] [MainThread/INFO]: 正在关闭 MCDR
[MCDR] [2022-04-17 17:38:58] [MainThread/INFO]: 正在关闭高级控制台
[MCDR] [2022-04-17 17:38:59] [MainThread/INFO]: bye
```
Mirror：
```
[MCDR] [2022-04-17 17:36:11] [MainThread/INFO]: MCDReforged正于Python 3.8.6环境中运行
[MCDR] [2022-04-17 17:36:11] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [2022-04-17 17:36:11] [TaskExecutor/INFO]: 没有插件变更; 已加载插件数: §72§r
[MCDR] [2022-04-17 17:36:11] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -Xms1G -Xmx2G -jar fabric-server-launch.jar nogui"
[MCDR] [2022-04-17 17:36:11] [MainThread/INFO]: 服务端正在以 PID 11244 运行中
[MCDR] [2022-04-17 17:36:12] [CheckUpdate/INFO]: MCDR 已为最新版
[MCDR] [2022-04-17 17:36:39] [TaskExecutor/INFO]: rcon 已连接
[MCDR] [2022-04-17 17:38:22] [TaskExecutor/INFO]: rcon 已断开连接
[MCDR] [2022-04-17 17:38:25] [MainThread/INFO]: 等待服务端进程停止
[MCDR] [2022-04-17 17:38:25] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [2022-04-17 17:38:25] [MainThread/INFO]: 服务端已关闭
[MCDR] [2022-04-17 17:38:25] [MainThread/INFO]: 正在关闭 MCDR
[MCDR] [2022-04-17 17:38:25] [MainThread/INFO]: 正在关闭高级控制台
[MCDR] [2022-04-17 17:38:44] [MainThread/INFO]: bye
```

**Comment by tangsu99** [comment]
> 你这个情况是间歇性的还是一直存在 我目前没存在你这个问题 你试试开启主服务器，然后开启镜像服，接着直接关掉镜像服，最后关掉主服务器，把logs文件夹里面的`MCDR.log`文件传给我

找到原因了qwq
插件AutoPluginReloader版本过时，更新至最新版无插件加载问题
出先问题的插件版本为1.0.1，最新版本为1.1.3
插件仓库：```https://github.com/TISUnion/AutoPluginReloader```
但是控制台输入命令还是不能正确地 发送到主服/镜像服
非常感谢能抽空帮我解决问题，因为我测试原因而导致没有定位到问题，很抱歉
我不确定问题（控制台输入命令不能正确地 发送到主服/镜像服）是如何导致的，能否提供一下建议

**Comment by tangsu99** [comment]
> 你这个情况是间歇性的还是一直存在 我目前没存在你这个问题 你试试开启主服务器，然后开启镜像服，接着直接关掉镜像服，最后关掉主服务器，把logs文件夹里面的`MCDR.log`文件传给我

找到原因了qwq
前面删掉了两条回复
发现问题 ：
1. 插件 AutoPluginReloader 版本过低，此前使用版本为1.0.1,现更新到1.1.3无问题
2. 主服MCDR config 内 start_command 使用bat启动服务器```start_command: run.bat```， 更改为直接使用命令行命令：```start_command: java -Xms1024M -Xmx8G -jar fabric-server-launch.jar nogui```无问题

插件仓库：```https://github.com/TISUnion/AutoPluginReloader```
但是控制台输入命令还是不能正确地 发送到主服/镜像服
非常感谢能抽空帮我解决问题，因为我测试原因而导致没有定位到问题，很抱歉
我无法确定问题（控制台输入命令不能正确地 发送到主服/镜像服）是如何导致的，能否提供一下建议

**Comment by tangsu99** [comment]
> 你这个情况是间歇性的还是一直存在 我目前没存在你这个问题 你试试开启主服务器，然后开启镜像服，接着直接关掉镜像服，最后关掉主服务器，把logs文件夹里面的`MCDR.log`文件传给我

搞得我也不是很确定上面描述的问题是否正确了，肯定的是与 AutoPluginReloader 有关系（大概。。我再多测试测试

**Comment by GamerNoTitle** [comment]
那我把AutoReloader加在一起再看看吧

**Comment by GamerNoTitle** [comment]
> > 你这个情况是间歇性的还是一直存在 我目前没存在你这个问题 你试试开启主服务器，然后开启镜像服，接着直接关掉镜像服，最后关掉主服务器，把logs文件夹里面的`MCDR.log`文件传给我
> 
> 搞得我也不是很确定上面描述的问题是否正确了，肯定的是与 AutoPluginReloader 有关系（大概。。我再多测试测试 更新插件之后这个问题不稳定出现，正在进一步查找原因
> 
> ```
> [MCDR] [2022-04-17 20:13:50] [MainThread/INFO]: MCDReforged正于Python 3.8.6环境中运行
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 刷新所有插件中
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 auto_plugin_reloader@1.1.3 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 biliwiki@1.0.0 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 carpet_bot_manager@0.3.0 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 chatbridge@2.2.0 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 crash_restart@1.0.0 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 daycount_nbt@2.2.0 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 here@1.2.2 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 info@0.0.2 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 join_motd@1.2.0 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 location_marker@1.3.1 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.4.1 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 mirror_server_reforged@1.0.3 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 playerlist_getter@1.0.0 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.4.3 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 timed_quick_backup_multi@1.0.1 已加载
> [MCDR] [2022-04-17 20:13:50] [TaskExecutor/INFO]: 插件 where_is@1.0.0 已加载
> [MCDR] [2022-04-17 20:13:51] [TaskExecutor/INFO]: 共加载: §716§r 个插件; 已加载插件数: §718§r
> [MCDR] [2022-04-17 20:13:51] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -Xms1024M -Xmx8G -jar fabric-server-launch.jar nogui"
> [MCDR] [2022-04-17 20:13:51] [MainThread/INFO]: 服务端正在以 PID 24724 运行中
> [MCDR] [2022-04-17 20:13:53] [CheckUpdate/INFO]: MCDR 已为最新版
> [MCDR] [2022-04-17 20:14:23] [TaskExecutor/INFO]: rcon 已连接
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 刷新所有变更的插件中
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 auto_plugin_reloader@1.1.3 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 biliwiki@1.0.0 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 carpet_bot_manager@0.3.0 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 location_marker@1.3.1 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 mirror_server_reforged@1.0.3 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.4.3 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 timed_quick_backup_multi@1.0.1 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 where_is@1.0.0 已卸载
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 chatbridge@2.2.0 (plugins\ChatBridge.pyz) 拥有与已存在插件 chatbridge@2.2.0 (plugins\ChatBridge.pyz) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 crash_restart@1.0.0 (plugins\CrashRestart-v1.0.0.mcdr) 拥有与已存在插件 crash_restart@1.0.0 (plugins\CrashRestart-v1.0.0.mcdr) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 daycount_nbt@2.2.0 (plugins\DayCountNBT-v2.2.0.mcdr) 拥有与已存在插件 daycount_nbt@2.2.0 (plugins\DayCountNBT-v2.2.0.mcdr) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 here@1.2.2 (plugins\Here-v1.2.2.mcdr) 拥有与已存在插件 here@1.2.2 (plugins\Here-v1.2.2.mcdr) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 info@0.0.2 (plugins\Info-v0.0.2.mcdr) 拥有与已存在插件 info@0.0.2 (plugins\Info-v0.0.2.mcdr) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 join_motd@1.2.0 (plugins\JoinMOTD-v1.2.0.mcdr) 拥有与已存在插件 join_motd@1.2.0 (plugins\JoinMOTD-v1.2.0.mcdr) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 minecraft_data_api@1.4.1 (plugins\MinecraftDataAPI-v1.4.1.mcdr) 拥有与已存在插件 minecraft_data_api@1.4.1 (plugins\MinecraftDataAPI-v1.4.1.mcdr) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/ERROR]: 插件 playerlist_getter@1.0.0 (plugins\PlayerList.py) 拥有与已存在插件 playerlist_getter@1.0.0 (plugins\PlayerList.py) 相同的 id，已移除
> [MCDR] [2022-04-17 20:15:02] [TaskExecutor/INFO]: 插件 simple_op@1.2.0 已加载
> ```

你的猜想是对的 AutoReloader 会在开镜像服工作目录变更的那一刻自动获取镜像服目录下的插件，查到同样的就给卸载了，而且在镜像服插件设置的5秒后自动切换回去后也不会自动再次加载，看样子可能是改目录这个操作在AutoReloader里面是被视为一个插件执行条件

**Comment by GamerNoTitle** [comment]
然而就目前来说，更改工作目录对于镜像服插件来说是必须的（要不然会出现主服务器的`logs/MCDR.log`被占用而导致镜像服无法启动），所以暂时来说，这个插件冲突修复不了

**Comment by tangsu99** [comment]
> 然而就目前来说，更改工作目录对于镜像服插件来说是必须的（要不然会出现主服务器的`logs/MCDR.log`被占用而导致镜像服无法启动），所以暂时来说，这个插件冲突修复不了

好的，非常感谢来帮助我，有一个想法：能不能让镜像服在另一个cmd窗口里启动，主服和镜像挤到一个里面好难受
暂时解决就不用 AutoReloader 插件了

**Comment by GamerNoTitle** [comment]
或许可以试试在镜像服里面不放 `AutoPluginReloader`，至少它不会卸载它自己，然后切换回主服务器工作目录时让它加载插件

以上是我的一个想法（我没尝试）

**Comment by tangsu99** [comment]
> 或许可以试试在镜像服里面不放 `AutoPluginReloader`，至少它不会卸载它自己，然后切换回主服务器工作目录时让它加载插件
> 
> 以上是我的一个想法（我没尝试）

试过了，还是会出现此问题

**Comment by GamerNoTitle** [comment]
> > 然而就目前来说，更改工作目录对于镜像服插件来说是必须的（要不然会出现主服务器的`logs/MCDR.log`被占用而导致镜像服无法启动），所以暂时来说，这个插件冲突修复不了
> 
> 好的，非常感谢来帮助我，有一个想法：能不能让镜像服在另一个cmd窗口里启动，主服和镜像挤到一个里面好难受 暂时解决就不用 AutoReloader 插件了

我一开始的想法确实是这样的，但是好像Windows的cmd传参有点小问题，然后后来我尝试用安静模式启动MCDR，但是这样切换目录就没有意义了（因为安静模式下MCDR不会受到切换目录的影响，还是会出现log文件被占用而无法启动），等我晚点再找个好的解决方式

**Comment by GamerNoTitle** [comment]
> > 或许可以试试在镜像服里面不放 `AutoPluginReloader`，至少它不会卸载它自己，然后切换回主服务器工作目录时让它加载插件
> > 以上是我的一个想法（我没尝试）
> 
> 试过了，还是会出现此问题

行吧，那看来目前的解决方案就是两个插件停用其中一个了

**Comment by tangsu99** [comment]
> > > 或许可以试试在镜像服里面不放 `AutoPluginReloader`，至少它不会卸载它自己，然后切换回主服务器工作目录时让它加载插件
> > > 以上是我的一个想法（我没尝试）
> > 
> > 
> > 试过了，还是会出现此问题
> 
> 行吧，那看来目前的解决方案就是两个插件停用其中一个了

谢谢帮助
