### ISSUE TITLE
JE1.18.1 MCDR2.6.1使用有时会在开启镜像服卡住

### ISSUE THREAD

**Issue by quizhizhe** [EMUnion/MirrorServerReforged#3]
使用的时MCSM9.5.0面板控制，在标题说的环境下，有时会在开启镜像服时卡住，使用!!msr stop指令无法关闭，镜像无法进去，只能通过强制重启MCDR才能再次使用，使用的MCDR插件有：1. Crash Restart; 2. Here; 3. Quick Backup Multi; 4. Stats Helper 5. Timed QBM

**Comment by GamerNoTitle** [comment]
有没有相关的log可以提供一下呢？

**Comment by quizhizhe** [comment]
> 有没有相关的log可以提供一下呢？

我试下解决编码问题先，后台的控制台一直在弹文本解析错误，MCDR里有大量这些信息，我重现问题后发一份MCDR的log上来

**Comment by GamerNoTitle** [comment]
> > 有没有相关的log可以提供一下呢？
> 
> 我试下解决编码问题先，后台的控制台一直在弹文本解析错误，MCDR里有大量这些信息，我重现问题后发一份MCDR的log上来

好的

**Comment by quizhizhe** [comment]
![image](https://user-images.githubusercontent.com/42761326/211968175-ec83b4e0-22e8-48a4-861e-08fddef4b20c.png)
这个是MCSM的后台记录，由于MCSM的log被自动，只有这一条所以没有上传log，里面的list是我输入的指令，输入没有反应，镜像已经进不去，执行!!msr stop无反应
以下文件是生存服log、MCDR log和生存服log
[Server.log](https://github.com/EMUnion/MirrorServerReforged/files/10397923/Server.log)
[MCDR.log](https://github.com/EMUnion/MirrorServerReforged/files/10397924/MCDR.log)
[Mirror.log](https://github.com/EMUnion/MirrorServerReforged/files/10397925/Mirror.log)

**Comment by GamerNoTitle** [comment]
MCDR版本？我猜是新版的MCDR对线程这一块做出了限制，如果是这样的话对于linux就得用nohup开镜像服了，然后Windows可能要用start？具体我到时候看看。

**Comment by GamerNoTitle** [comment]
（因为我在我们服务器装自制的QQbot的时候也发现了这个问题

**Comment by quizhizhe** [comment]
> MCDR版本？我猜是新版的MCDR对线程这一块做出了限制，如果是这样的话对于linux就得用nohup开镜像服了，然后Windows可能要用start？具体我到时候看看。

OK，那只能将就用着先 😢

**Comment by GamerNoTitle** [comment]
没事 现在改 改好了发

**Comment by GamerNoTitle** [comment]
刚推送了一个新版本的MSR，可以试试那个，用了`nohup`的方式来开镜像服，不过这样的话控制台不会有任何信息的输出（或许整合某些用户的需求？）

**Comment by quizhizhe** [comment]
> 刚推送了一个新版本的MSR，可以试试那个，用了`nohup`的方式来开镜像服，不过这样的话控制台不会有任何信息的输出（或许整合某些用户的需求？）

好耶，太棒了

**Comment by GamerNoTitle** [comment]
好的
