### ISSUE TITLE
无法在无图形界面的linux系统上使用!!msr start命令？

### ISSUE THREAD

**Issue by RedSnailMC** [EMUnion/MirrorServerReforged#6]
在服务器使用的还是windows系统时 此命令还可以正常执行
但在无图形界面的debian linux上似乎就不灵了

**Comment by GamerNoTitle** [comment]
我无图形界面的ubuntu是可以的哦

**Comment by GamerNoTitle** [comment]
你用的是不是这个版本。。。
![Screenshot_2023-04-05-11-17-43-693_com.github.android.jpg](https://user-images.githubusercontent.com/28426291/229972745-b69603ab-eb26-4f91-ab1e-75920a743b64.jpg)
